#!/usr/bin/env bash
#!This script displays numbers from 1 to 10 including FizzBuz when the number is multiplie by 3, 5 Fizz when the number is multiplie by 3,Buzz when the number is multiplie by 5
for ((i=1; i<=100; i++)); do
  if (( i % 15 == 0 )); then
    echo "FizzBuzz"
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  elif (( i % 5 == 0 )); then
    echo "Buzz"
  else
    echo "$i"
  fi
done
