#!/usr/bin/env bash                                                
#This bash script displays number from 1 to 20 and on 4th line it should include bad luck from china and on 9th line it should diplay bad luck from Japan and on 17thh line it should dipslay bad luck from Italy
i=1
while [ $i -le 20 ]; do
  case $i in
    4)
      echo "$i"
      echo "bad luck from China"
      ;;
    9)
      echo "$i"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$i"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  i=$((i + 1))
done
