#!/usr/bin/env bash
#!This script displays content of the current directory in a list format where only the part of the name after the first dash is displayed
files="$(ls)"
for f in $files;
do
echo "$f" | cut -d "-" -f2
done
