#!/usr/bin/env bash
#!This script displays content of the current directory in a list format where only the part of the name after the first dash is displayed
for file in *; do
  name="${file#*-}"
  echo "$name"
done
